dict_palabras_dificiles = {

    "Abstracción": "Estilo de arte que propone una realidad nueva.",
    "Acantilado": "Opción 1: es una pared de roca muy alta que está pegada al mar.  Opción 2: son montañas muy altas que están encima del mar.",
    "Accesibilidad": "Es la característica que tienen los espacios y documentos donde es fácil acceder y entender.",
    "Accesible": "es una zona en la que las personas con problemas de movilidad pueden entrar sin dificultad",
    "Acequia": "cauce pequeño que lleva agua.",
    "Acetato": "Es un tipo de papel transparente que usamos en las manualidades.",
    "Acidificación": "Es cuando la contaminación del aire hace que el agua de los océanos se vuelva más ácida y esto pone en peligro la vida de todas las especies marinas como los peces, almejas, erizos, corales.",
    "Acoso sexual": "Es cualquier palabra o comportamiento relacionado con el sexo que una persona usa para perseguir, atacar o asustar a otra.",
    "Acoso sexual por razón de sexo": "Discriminar o tratar mal a una persona por pertenecer a un sexo o a otro.",
    "Actas digitales": "Son documentos que tienen escritos los acuerdos de una reunión. La información se recoge con medios informáticos.",
    "Actividad lúdica": "Actividades que se hacen en el tiempo libre para divertirse y entretenerse.",
    "Activista medioambiental": "Es una persona que participa de forma responsable en actividades para cuidar el planeta. ",
    "Actuar de oficio": "Por ejemplo cuando la policía conoce un delito y actúa sin que alguien haya denunciado. ",
    "Agallas": "frutos de forma redonda. que se forman cuando un insecto pica a la planta.",
    "Aguadora": "mujer que lleva o vende agua.",
    "Aguijón": "pincho pequeño y puntiagudo.",
    "Albir": "es un pueblo de Alicante. Está entre la Sierra Helada y Benidorm.",
    "Albufera": "es una laguna de agua salada que se forma en tierras bajas al lado del mar.",
    "Alfarrassador": "El alfarrassador es la persona que mide a ojo la cantidad de fruta que hay en un campo",
    "Alianza": "Es un acuerdo entre varias partes para conseguir un objetivo.",
    "Alioli": "salsa hecha con aceite y ajo.",
    "Aljibe": "Es un depósito que esta debajo de la tierra y sirve para recoger el agua de la lluvia.",
    "Alojamiento": "lugar o casa donde vive y duerme una persona",
    "Alteración": "Es cuando algo cambia y no está en su estado original. ",
    "Alternando": "las hojas crecen unas detrás de las otras y ninguna es igual a la siguiente.",
    "Ánfora": "Es un jarrón de barro",
    "Apodo": "es cuando llaman a una persona por un nombre que no es el suyo. Ejemplo: Su nombre es Antonio y le llaman el rubio.",
    "Arbolado": "zona que está llena de árboles y plantas.",
    "Arbusto Perenne": "es un árbol con tronco corto que mantiene las hojas durante todo el año.",
    "Archilaúd": "Es un instrumento musical de cuerda parecido a la guitarra.",
    "Arcilla": "tierra formada por restos de minerales que cuando se mezcla con agua se le puede dar forma. Cuando se calienta se hace dura.",
    "Aromática": "Planta que tiene muy buen olor.",
    "arqueología": "es una ciencia que estudia los pueblos antiguos a través de los restos y objetos que encuentra",
    "Arqueológico": "la arqueología estudia los monumentos y los objetos muy antiguos que están enterrados bajo tierra o bajo el mar. ",
    "Arqueólogo": "persona que estudia y busca restos antiguos para saber cómo vivían las personas de otras épocas.",
    "arqueólogo": "es una persona que estudia el pasado del hombre a través de los restos que encuentra como huesos, cerámica, herramientas.",
    "Arte abstracto": "Representa formas que no son reales.",
    "arte contemporáneo": "es el arte del siglo 20.",
    "Arte macro esquemático": "es un estilo de pintura rupestre que se descubrió en 1980 en la Península Ibérica sobre todo en Alicante.",
    "Arte rupestre": "Son las pinturas o dibujos que hacían los seres humanos en las rocas hace miles de años.",
    "Arte rupestre": "son pinturas o dibujos que hacían dentro de las cuevas los habitantes de la Prehistoria ",
    "artificial": "es algo hecho por el hombre.",
    "Asamblea de Naciones Unidas": "Que también se llama ONU. Es una asamblea que está formada por personas que representan a 193 países del mundo.",
    "Asentamiento Ibérico": "Es un lugar donde vivieron los íberos.",
    "Asesora jurídica": "Es una profesional experta que nos puede aconsejar sobre leyes",
    "Atención Temprana": "es atender al bebé y al niño para desarrollar sus capacidades: físicas intelectuales sociales.",
    "Audiencia provincial de Alicante": "Edificio o sede de los juzgados de la provincia de Alicante. ",
    "Auditorio": "Lugar donde celebran conciertos y otros espectáculos",
    "auditorio": "lugar donde celebran conciertos y otros espectáculos",
    "Autodeterminación": "Es cuando una persona toma sus propias decisiones.",
    "Autoestima": "Es cuando una persona está bien con él mismo.",
    "Autoritario": "Persona que usa su poder para que hagan lo que él quiere.",
    "AVE": "significa Alta Velocidad Española y es como un tren pero que va mucho más rápido.",
    "Bahía": "es la entrada del mar en la costa.",
    "bailaor": "Es un hombre que canta flamenco.",
    "Bambú": "Es una planta alta que tiene forma de caña.",
    "Banda Sinfónica": "grupo de músicos que tocan diferentes instrumentos.",
    "Barrios marginales": "Son barrios que son muy pobres.",
    "Barroco": "Opción 1: es un estilo de arte que pone muchos adornos en sus obras. Opción 2: estilo de arte que se caracteriza por poner muchos adornos en sus obras.",
    "Basílica": "iglesia de la época romana en forma de rectángulo",
    "Baya": "fruto carnoso con forma redondeada.",
    "Belén": "Es la representación con figuras del nacimiento de Jesús.",
    "Berberiscos": "piratas del norte de África.",
    "Bien de interés cultural": "especie de título que concede el Estado Español para proteger y conservar ese bien y que todo el mundo pueda disfrutar de él. ",
    "Bienes económicos": "Son las cosas que poseemos y que valen dinero.",
    "Bodega": "es un espacio de un barco que sirve para guardar los productos o mercancías.",
    "Bodegón": "Es una obra de arte que representa: - animales -flores -otros objetos Pueden ser naturales o hechos por las personas.",
    "Bodegones": "Son dibujos o pinturas que representan alimentos y recipientes como por ejemplo vasos o jarras.",
    "Boyas": "son objetos flotantes que encontramos en el mar y sirven para orientar a los barcos.",
    "Breve": "Es una obra de teatro que dura poco tiempo.",
    "Cabalgata de los Reyes Magos": "es un desfile con muchas personas, bandas de música, caballos y otros animales, para celebrar que vienen los Reyes Magos de Oriente.",
    "Caballero Cubierto": ": El Caballero Cubierto de Orihuela, es la persona elegida cada año por la corporación municipal de la ciudad, por su amor y lealtad a la ciudad, para llevar el pendón-estandarte que abre la procesión del Santo Entierro de Cristo en Semana Santa.",
    "Cabo": "parte de la tierra que se introduce en el mar.",
    "Caduca": "hoja que pierde el color verde en otoño. Entonces la hoja muere y cae al suelo.",
    "cala": "playa pequeña que a veces tiene rocas alrededor. ",
    "Calafatería": "Es la forma de unir la madera de los barcos con un material especial para que no entre agua.",
    "Calidad del agua": "el agua tiene calidad cuando está limpia y no está contaminada.",
    "Cáliz": "hojas verdes que protegen los pétalos de la flor.",
    "Cambio climático": "Es el cambio de temperatura que se está produciendo en el planeta tierra a causa de la contaminación de las personas.",
    "Canales": "conducto hecho por personas por donde pasan líquidos o sustancias y se transportan de un sitio a otro.",
    "cantaora": "Es una mujer que canta flamenco.",
    "Capacidad jurídica": "Es cuando la persona puede ejercer sus derechos y obligaciones por sí mismo sin necesitar el permiso de otra persona. Por ejemplo: firmar un contrato de trabajo.",
    "Capataz": "es la persona que manda y vigila a un grupo de trabajadores.",
    "Capilla": "Es una parte pequeña de la iglesia donde rezamos",
    "capilla": "es una parte de la iglesia donde se reza",
    "Cápsula": "quiere decir que tiene forma de píldora como algunas medicinas.",
    "Carta de nupcias": "La carta de nupcias o capitulaciones matrimoniales: es un documento en el que se establece la organización económica y cualquier otro acuerdo personal que esté relacionado con los bienes del matrimonio. Los pactos pueden ser a favor de ellos o de sus hijos y pueden ser válidos durante el matrimonio o cuando el matrimonio termine, si esto ocurre.",
    "Cartaginesa": "que era de una ciudad antigua de África llamada Cartago",
    "Cartela": "Trozo de cartón que se usa como tarjeta para poner o escribir algo. Este trozo también puede ser de otros materiales como la madera. ",
    "Casco antiguo": "parte más antigua de la ciudad",
    "casco antiguo": "parte más antigua de la ciudad.",
    "catedrático": "Es un profesor de instituto o universidad que tiene un nivel superior.",
    "Centro de interpretación": "es un espacio donde se enseña y aprende sobre el bien cultural que se visita. ",
    "Centros Especiales de Empleo": "Son empresas que dan trabajo a las personas con discapacidad. Este trabajo es adecuado a sus características personales y facilita que las personas con discapacidad puedan trabajar en cualquier empresa.",
    "Cerámica cardial": "nombre de la primera cerámica y la forma en que se trabajaba y decoraba",
    "Certificado de nacimiento": "Es un documento donde se apunta la fecha, el lugar y la hora de nacimiento de una persona.",
    "Césped": "planta con hojas finas de color verde que se plantan en los jardines y en los campos de futbol.",
    "Cibercafés": "cafetería que tiene ordenadores para utilizar internet.",
    "ciclo": "Son diferentes actividades relacionadas con el mismo tema.",
    "Circular": "Es un documento que se utiliza para dar información a un grupo de personas. ",
    "Circulo cromático de Itten ": "es un círculo de colores formado por 12 colores.",
    "Ciudad islámica": "ciudad del islam",
    "Ciudad sostenible": "Es una ciudad que respeta el medio ambiente.",
    "Civilización": "Costumbres, ideas, creencias, cultura y conocimientos de un grupo de personas en un momento de la historia. ",
    "claustro": "pasillo que rodea un patio",
    "Clave": "Es un instrumento musical con teclado parecido a un piano. de cuerda parecido al violín, pero más grande.",
    "Clima extremo": "Es cuando una zona tiene tormentas fuertes de viento o nieve, granizo, huracanes, olas de calor o falta de lluvias.",
    "coca": "masa de harina que se hace a fuego lento, a la que podemos añadir distintos ingredientes",
    "coctel ": "Un cóctel es una bebida hecha con mezcla de licores, zumos y otros ingredientes.",
    "coctelería": "es un local que sirve cócteles. Un cóctel es una bebida hecha con mezcla de licores, zumos y otros ingredientes.",
    "Código Civil": "en él están todas las normas de derecho civil de carácter común en España y que se usan en los territorios que no tienen derecho civil foral",
    "cofradía": "es una asociación o grupo de personas que se unen para hacer juntas actividades de tipo religioso.",
    "Cofradía de pescadores": "persona que forma parte de un matrimonio",
    "Cogollo": "punta tierna de la rama o tallo de un vegetal.",
    "Color Púrpura": "color parecido al violeta.",
    "Colorante": "material que utilizamos para cambiar el color de algo.",
    "Colores primarios": "Son los colores principales: rojo amarillo azul ",
    "Comerciar": "comprar, vender o intercambiar productos para ganar dinero o cosas.",
    "Comisaria": "Es la persona que organiza la exposición porque sabe mucho de arte.",
    "comisarios": "Son las personas que organizan la exposición porque saben mucho de arte.",
    "Comparsa": "grupo de personas que participan en una fiesta popular.",
    "Competencias digitales" :"Usar las tecnologías de la información y la comunicación de forma creativa, crítica y segura para alcanzar los objetivos relacionados con el trabajo, aprendizaje, uso en el tiempo libre, inclusión, participación en la sociedad, etc.",
    "Comunicación positiva": "Es una forma de decir lo que pensamos y sentimos sin hacer daño a los demás. ",
    "Comunidad autónoma": "territorio que está formado por varias provincias que tienen las mismas leyes.",
    "Comunidad Autónoma": "los territorios con una historia o cultura común se pueden unir para formar una Comunidad Autónoma.",
    "Concertado": "Es un centro privado, pero recibe una ayuda económica. ",
    "Concienciación social": "La capacidad que tienen las personas para comprender los problemas y necesidades de la gente de nuestra comunidad.",
    "Concienciar": "Dar a conocer información de un tema para que las personas se den cuenta de un problema.",
    "Congreso de los Diputados": "Es el grupo de políticos que representan a los ciudadanos españoles.",
    "Conjunto histórico y bien de interés cultural": "son lugares o monumentos que están protegidos",
    "conquistar": "quitar un lugar a otras personas por la fuerza. ",
    "Consorcio": "es una agrupación",
    "Consumidores": "son las personas que compran o necesitan un producto o servicio. ",
    "Contrato indefinido": "Es un documento que relaciona a una empresa y un trabajador y que no tiene fecha final. ",
    "Convención": "Es un acuerdo muy importante entre países sobre un tema.",
    "Convenio Marco de la Organización Mundial de la Salud para el Control del Tabaco": "Acuerdo al que llegaron todos los países para disminuir el abuso del consumo de tabaco",
    "Convocatoria pública": "Es el anuncio público de un acto para que las personas interesadas puedan participar.",
    "Cónyuge": "Persona que forma parte de un matrimonio",
    "Copa": "parte del árbol formada por ramas, hojas y flores.",
    "Coral": "Es un grupo de cantantes que pueden estar acompañados de instrumentos.",
    "Corrida de toros": "es una fiesta que consiste en torear toros a pie o a caballo en un lugar cerrado que se llama plaza de toros.",
    "Cortes Valencianas": "eran las encargadas de hacer y votar las leyes del Reino de Valencia.",
    "Cualidades": "Son las características buenas de una persona.",
    "Cualificación básica": "Formación para personas que han abandonado la educación reglada como el instituto sin haber conseguido los objetivos y que se adapta a lo que necesitan.",
    "Cubismo": "Estilo de arte que representa la realidad con figuras geométricas.",
    "Cultivar": "Plantar semillas en la tierra para conseguir alimentos. ",
    "Cultura": "Forma de vida de un país o territorio",
    "Cultura ibérica": "Forma de vida de la península ibérica que está formada por España y Portugal",
    "Dama de Cabezo Lucero": "Es una escultura que representa la cabeza y la parte superior del cuerpo de una mujer. No sabemos si es una persona o una diosa. ",
    "danza contemporánea": "Es la danza actual. Es distinta al baile clásico.",
    "Dársena": "Parte que se construye en un puerto para proteger de las corrientes a los barcos.",
    "De oficio": "Por ejemplo cuando la policía conoce un delito y actúa sin que nadie haya denunciado.",
    "Deforestación": "Es cuando un bosque se queda sin árboles y plantas.",
    "Demanda": "Es la cantidad de productos y servicios que necesita la empresa en ese momento. Pueden ser muchos o pocos.",
    "Democracia representativa": "Es el sistema de organización donde los ciudadanos eligen unos representantes para que tomen las decisiones por ellos.",
    "Derecho": "es el conjunto de normas que sirven para regular las relaciones entre las personas o los países.",
    "Derecho romano": "eran las leyes que tenían que cumplir los ciudadanos y ciudadanas en la Antigua Roma.",
    "Derechos fundamentales": "Son los derechos más importantes de las personas. Por ejemplo: la vida, igualdad, libertad y muchos más.",
    "Desarrollo motor": "Es el proceso en el que los niños aprenden a moverse y a usar su cuerpo. ",
    "Desarrollo personal": "son las actividades y cosas que hacemos para mejorar y crecer como personas. ",
    "Desarrollo sostenible": "Es la capacidad de una sociedad para cubrir las necesidades básicas de las personas respetando el medio ambiente y sin perjudicar el desarrollo y los recursos de las personas en el futuro.",
    "Desertificación": "Es cuando las tierras que antes se podían plantar se vuelven secas y ya no se pueden plantar.",
    "Diagnosticar": "Proceso para identificar una enfermedad, lesión o algo que afecta a una persona. ",
    "Días hábiles": "son los días que sirven para contar el plazo de tiempo para hacer una actividad.",
    "Digitalización": "Es el proceso de convertir información o medios escritos a valores que puedan ser procesados por ordenadores.",
    "Dignidad": "Que respeten todos sus derechos.",
    "Diputación": "Es el gobierno de una provincia",
    "Diputación": "es el gobierno de una provincia.",
    "DiscoverEU": "Es un programa del Erasmus+ para que los jóvenes y estudiantes puedan conocer Europa en tren",
    "Discriminación": "Rechazar a una persona por pensar que es diferente.",
    "Distrito": "partes en que se divide un territorio de un pueblo para gestionar el dinero de un pueblo de forma correcta. ",
    "Doctor en derecho": "Es una persona experta en el estudio del derecho.",
    "Doctora en filología": "Es una persona experta en el estudio de la lengua.",
    "Donación": "Una donación es cuando damos a una persona una cosa y no esperamos nada a cambio.",
    "Donación": "dar un bien a otra persona.",
    "Dunas": "son pequeñas colinas de arena que forma el viento en la playa.",
    "Dunas": "son pequeñas montañas de arena que forma el viento en la playa.",
    "Ecosistema": "Ecosistemas son los lugares donde viven los seres vivos y tienen todo lo necesario para vivir. ",
    "Edad Contemporánea": "etapa de la Historia desde el final del siglo 18 hasta el siglo 20. ",
    "Edad de bronce": "Opción 1: Es el periodo de la prehistoria donde se descubre y trabaja el metal del bronce.  Opción 2: es un periodo de la prehistoria en el que se fabricaron objetos y armas de bronce. La prehistoria es el primer periodo de la historia. El bronce es un metal.",
    "Edad Media": "Es el periodo de tiempo que va desde el siglo 5 hasta finales del siglo 15. ",
    "Edad moderna": "Es el periodo de tiempo que va desde el siglo 15 hasta el siglo 18",
    "Edificio civil": "Es un edificio que sirve para dar un servicio a la ciudadanía. Por ejemplo:  aeropuertos puentes puertos ",
    "Educación preescolar": "Es la enseñanza de 0 a 6 años",
    "Educación primaria": "Es la enseñanza que todos los niños y niñas de 6 a 12 años tienen que hacer. ",
    "Educación secundaria": "Es la enseñanza que todos los niños y niñas de 12 a 16 años tienen que hacer",
    "Embajadora de conciencia": "Es un premio que le dan a una persona porque defiende los derechos humanos y se enfrenta a las injusticias haciendo que la sigan muchas personas. ",
    "Empoderamiento": "Opción1: Conseguir poder e independencia por parte de un grupo desfavorecido para mejorar su situación social, en este caso las mujeres. Opción2: Tener poder para valerse por sí mismo.",
    "Encía": "tejido que rodea la base de los dientes. Es de color rosa.",
    "Encurtidos": "Son verduras o frutos que se conservan en vinagre, sal y hierbas aromáticas y tienen un sabor ácido.",
    "Energía renovable": "Son aquellas energías que provienen de una fuente natural como el agua, el sol y el viento.",
    "Energía sostenible": "Energía que se consigue de la naturaleza y no contamina: viento sol ríos y mares lluvia ",
    "enfangado": "lleno de barro",
    "Entidad": "asociación de personas que se dedican a una actividad de trabajo. Por ejemplo, una entidad es: una empresa, una asociación o un organismo. ",
    "epidemia": "hay una epidemia cuando una enfermedad grave se contagia a muchas personas",
    "Época de cría": "desde que ponen los huevos hasta que nacen las crías y las crías aprenden a volar. La época de cría dura unos 6 meses.",
    "Época islámico medieval": "Periodo de tiempo dentro de la época medieval con influencia de la cultura islámica. Es del Siglo VIII (8) al Siglo XIII (13)",
    "época moderna": "es un periodo de tiempo que va desde el siglo 15 hasta el siglo 18.",
    "Equipo seri": "Grupo de personas con discapacidad intelectual del Centro Ocupacional Terramar de APSA que participa en el proyecto Tirando del Hilo.",
    "Erasmus" : "Es un programa de intercambio y desplazamiento durante unos meses de estudiantes de la Unión Europea para apoyar: la educación, la formación, la juventud,  el deporte",
    "Ermita": "Es una iglesia pequeña",
    "Esbelto": "que tiene el cuerpo alto y largo.",
    "Escudo": "es el símbolo de una ciudad.",
    "Esgrima": "es un deporte en el que se enfrentan 2 personas con una espada protegidas por una careta y un traje especial.  Gana quien antes consigue tocar con el arma al oponente un número de veces.  ",
    "espacios públicos": "Son lugares que todas las personas tienen derecho a usar. Por ejemplo: calles plazas jardines carreteras hospitales bibliotecas parques",
    "Especies exóticas invasoras": "Son animales y plantas que crecen fuera de su lugar natural y hacen daño a los ecosistemas.",
    "espectáculo": "representación que se hace para entretener. ",
    "Espiga": "es la forma que tiene algunas flores parecidas a una pluma.",
    "Espinilla": "Parte de delante de la pierna que va desde la rodilla hasta el tobillo",
    "Estable": "algo que no cambia cuando pasa el tiempo",
    "Estambre": "parece una antena pequeña que nace dentro de la flor y puedes verla desde fuera.",
    "Estampa religiosa": "un trozo de papel en el que está impreso un santo y por detrás una oración.",
    "Estampar": "Escribir o dibujar sobre un material haciendo presión.",
    "Estandarte": "una pieza de tela de forma cuadrada o rectangular, con una imagen o símbolo, que está sujeta a un palo. Antes lo llevaban los caballeros andantes y ahora lo usan para actos civiles o religiosos.",
    "Estatuto de Autonomía": "son las normas más importantes de cada Comunidad Autónoma. La Constitución reconoce los Estatutos de Autonomía. Los estatutos tienen: • El nombre de la Comunidad Autónoma • El territorio y fronteras de la Comunidad Autónoma • El nombre de las instituciones de la Comunidad Autónoma. • Lugar donde están las Instituciones de la Comunidad Autónoma. • Las competencias que tiene la Comunidad Autónoma • Los idiomas oficiales",
    "Estatuto de los trabajadores": "es la ley que explica los derechos y las obligaciones de las personas que trabajan",
    "Estilo abstracto": "es un estilo artístico formado por colores, líneas y figuras.",
    "Estupefacientes": "Son medicamentos que se utilizan para tratar algunos trastornos y que pueden crear adicción.",
    "Europa": "es uno de los continentes que forman el planeta Tierra. España está en Europa.",
    "exclusión": "Dar de lado a una persona o marginar.",
    "Exigir": "ordenar y reclamar algo cuando crees que tienes derecho a conseguirlo. ",
    "Exótico": "Es un lugar muy diferente a lo que estamos acostumbrados a ver.",
    "Expectativas": "Son las cosas que quieres conseguir",
    "Explanada": "terreno llano",
    "Explotación salinera": "lugar donde trabajan para conseguir sal",
    "Explotación sexual": "Es cuando una persona gana dinero obligando a otras personas a tener relaciones sexuales sin su permiso.",
    "Exportaciones": "Es la actividad comercial que consiste en vender productos y servicios a otro país.",
    "Exposiciones permanentes": "una muestra de objetos que están siempre. Nunca se cambian por otros objetos.",
    "Exposiciones temporales": " una muestra de objetos que están solo durante un tiempo. Normalmente son objetos que viene de otros países.",
    "Fenicios": "era un pueblo que vivía en la costa oriental del Mar mediterráneo. Eran muy buenos navegantes, muy buenos compradores y vendedores, y conocían la escritura.",
    "Férula": "Tabla o molde que es flexible y resistente que se usa para que no se mueva alguna parte del cuerpo o que se mueva sólo como queramos.",
    "Ficus": "es un árbol de hojas grandes y fuertes.",
    "Finanzas": "Son todas las actividades que tienen relación con el dinero.",
    "Fiscal": "abogado que trabaja para el Estado. ",
    "Flamenco": "Es un ave muy bonita de color rosa. Tiene las patas y el cuello largo. Su cabeza es pequeña.",
    "Foguera": "Escultura o monumento de arte que se construye para quemarlo. También la llaman Hoguera. ",
    "Formas de vida": "significa seres vivos. Por ejemplo: animales y plantas.",
    "Fortaleza": "Construcciones para defender un lugar.",
    "Fósiles": "restos de vidas muy antiguas que se conservan en las rocas.",
    "foso": "hoyo hondo y alargado que rodea un castillo.",
    "Funciones ejecutivas": "Son las actividades de la mente más difíciles que necesitamos por ejemplo para: •        Tomar decisiones •        Organizarnos •        Poner objetivos •        Anticiparnos •        y otras más",
    "Ganadero": "Persona que trabaja cuidando y alimentando a animales para que las personas después puedan comérselos.",
    "Garrochista": "hombre que pica a los toros con una vara larga que termina en punta durante las corridas de toros.",
    "Genoveses": "son los ciudadanos de Génova. Génova es una ciudad del país que se llama Italia. ",
    "Geología": "es la ciencia que estudia cómo se formó la tierra y los materiales que la componen.",
    "Gótico": "Estilo de arte que se caracteriza por construir iglesias y edificios muy altos en los que entra mucha luz",
    "Guerra de la independencia": "es una guerra que hubo en España en el siglo 19.",
    "Guitarra barroca": "Es un tipo de guitarra que usaban en la época barroca.",
    "Gymkhana": "juego en el que tienes que hacer diferentes pruebas.",
    "Habilidades socio profesionales": "Son las habilidades para relacionarse bien con las demás personas en el trabajo.",
    "Hashtags": "es una palabra clave para nombrar el contenido de un tema en redes sociales. Empieza siempre con el símbolo almohadilla #",
    "hectárea": "es una forma de medir espacios grandes.  Por ejemplo: una hectárea es más o menos como 2 campos de fútbol juntos.",
    "Hermafrodita": "flore, o animal que tiene el aparato reproductivo masculino y femenino a la vez.",
    "Hepatitis B": "Es una enfermedad que no se cura y se contagia por la sangre la saliva o el semen.",
    "Hércules": "nombre del equipo de fútbol de Alicante",
    "Herencia": "es cuando una persona muere y deja a otras personas: dinero casas terrenos y otras cosas de valor",
    "Herencia": "La herencia son las cosas o propiedades que recibimos de una persona tras su muerte.",
    "Hierba crasa": "es un tipo de planta que tiene el tallo, la raíz o las hojas más gruesas. Así puede guardar más cantidad de agua dentro.",
    "Historiadora": "persona que estudia la historia",
    "Hockey": "deporte en que 2 equipos compiten por meter una pelota pequeña en la portería con ayuda de un bastón largo ",
    "Hogueras de San Juan": "son las fiestas más importantes de la ciudad de Alicante.",
    "Hormigón": "es un material muy duro y resistente.",
    "hoyo": "agujero circular que se hace en la tierra o en otra superficie",
    "Humanidad": "Es el conjunto de todos los seres humanos",
    "íberos": "son las personas que vivían en España antes de llegar los romanos.",
    "Ideas preconcebidas": "Son las ideas que nos hacemos antes de tener toda la información sobre las cosas.  ",
    "Ilegal": "Es hacer cosas prohibidas por la ley.",
    "Ilustrar": "Hacer el diseño que hemos pensado.",
    "Impuestos": "Dinero que los ciudadanos tienen que pagar al Estado para que haga carreteras, colegios y hospitales",
    "Indígena": "Persona que vive en un territorio respetando las costumbres y forma de vida antiguas.",
    "Influencia": "efecto o cosa que hace una cosa en otra",
    "Infraestructura rural": "Tener transporte en las granjas, agua para regar, electricidad y graneros para almacenar los cultivos.",
    "Infraestructuras": "Es un conjunto de servicios como el transporte, la energía y las comunicaciones que son necesarios para que funcione bien un país.",
    "Insectos": "moscas - mosquitos - escarabajos - hormigas - saltamontes - y muchos más",
    "Inserción laboral": "Participar en el trabajo con las mismas oportunidades y condiciones que todas las personas.",
    "Inspiración creativa": "Cuando una persona crea nuevas ideas. ",
    "Institución pública": "Es una organización para toas las personas que se ha creado para hacer actividades: políticas, culturales, científicas, sociales, etc.",
    "Instituciones": "Son organizaciones que se han creado para hacer actividades políticas, culturales, científicas o sociales.",
    "Instituciones públicas": "Es una organización para todas las personas que se ha creado para hacer actividades: -políticas -culturales -científicas -sociales",
    "Instrumentos polifónicos": "Son instrumentos que pueden dar diferentes sonidos a la vez. Por ejemplo: ● Laúd ● Guitarra ● Órgano ● Piano",
    "Integración": "Es cuando un grupo de personas acepta a otra sin importar sus características. Es lo contrario a la discriminación. ",
    "Integrar": "Es cuando un grupo de personas acepta a otra sin importar sus características. Es lo contrario a la discriminación. ",
    "Intervención psicopedagógica": "Planificar todo lo que tiene que ver con la educación: el análisis de necesidades poner objetivos y metas y evaluar ",
    "Invertir": "Es usar una cantidad de dinero en un país para mejorar su situación.",
    "Islas Baleares": "son unas islas de España.",
    "Islas Fidji": "Son unas islas que están en el Océano Pacífico y cerca de Australia.",
    "Itinerario": "Es una ruta o un recorrido",
    "Juego cooperativo": "juegos donde los jugadores colaboran juntos para conseguir un objetivo.  Se gana y se pierde en grupo. ",
    "juegos interactivos": "en estos juegos la persona y el juego se relacionan entre ellos.",
    "Juegos paralímpicos": "Son como los Juegos Olímpicos pero los participantes son personas con algún tipo de discapacidad.",
    "Kayac": "Es un deporte que se practica en el agua en una canoa con remos.",
    "Kayak": "Opción 1: canoa con remos.  Opción2: es un deporte que se practica en una canoa con remos.",
    "Kilómetros": "1 kilómetro son mil metros.",
    "La Constitución": "es la norma más importante de España. Todos los poderes públicos y los ciudadanos tienen la obligación de respetarla. Se aprobó en el año 1978.",
    "Las Cortes valencianas": "Es el grupo de políticos que representan a los ciudadanos de la Comunidad",
    "Legumbre": "es una semilla que crece dentro de la planta y que se puede comer.",
    "Leñoso": "de madera muy fina.",
    "Ley inconstitucional": " una ley es inconstitucional cuando no cumple o no respeta la Constitución que es la norma más importante del país.",
    "Lideresa": "Mujer que lidera o dirige un pueblo indígena.  ",
    "Limitado": "Algo que tiene un principio y un final. Por ejemplo: -1 semana -10 días - 2 semanas",
    "Lírica": "Es una forma de cantar con pocos instrumentos parecida a la ópera.",
    "Lobo Marino": "animal marino parecido a la foca.",
    "Lonja de pescado": "edificio donde los pescadores venden el pescado.",
    "Los ecosistemas terrestres": "Son lugares donde viven seres vivos y tienen todo lo necesario para vivir. Hay distintos tipos de ecosistemas terrestres: -        desiertos -        selvas -        praderas -        bosques",
    "Lucentum": "es el nombre de una antigua ciudad romana que hay en Alicante.",
    "Magistrada": "parecido a un juez, pero de un órgano superior.  ",
    "Mamífero": "animal que toma leche de la teta de su madre cuando es pequeño.",
    "Manutención": "mantener a una persona.  Por ejemplo, darle comida o lo que necesite para vivir. ",
    "maqueta": "es la copia de una construcción a un tamaño más pequeño.",
    "Marco de Sendai": "Son instrucciones de la ONU. La ONU es la Organización de Naciones Unidas. Estas instrucciones dicen qué hacer cuando hay un desastre.",
    "Mare Nostrum": "es el mar Mediterráneo.",
    "Marina alta": "Es una zona que está al norte de Alicante.",
    "mármol": "es una piedra que se usa para la construcción y para hacer esculturas. Hay mármol de distintos colores.",
    "Mármol": "Es una piedra que usamos para la construcción y para hacer esculturas",
    "Mascletá": "es un conjunto de petardos muy fuertes que se explotan para hacer mucho ruido y son típicos de las fiestas más importantes de Alicante que se llaman Hogueras de San Juan.",
    "Máster": "Curso para saber más sobre un tema.",
    "mástil": "palo largo de un barco que sirve para colocar las velas.",
    "Material islámico": "Son objetos o herramientas de la cultura árabe.",
    "Meet": "Es la plataforma para videollamadas de la aplicación Google. Se utiliza para hacer reuniones, talleres o cursos. ",
    "Mesa redonda": "Es una charla en la que participan varias personas",
    "Metalúrgicos": "artesanos que se dedicaban a crear objetos de metal.",
    "Método arqueológico": "Método arqueológico: es conjunto de normas que utilizan los arqueólogos para estudiar los restos históricos antiguos.",
    "Mezquita": "edificio parecido a una iglesia que usan los musulmanes",
    "Migrantes": "Personas que van de su país a otro diferente para estar un tiempo o quedarse a vivir para siempre.",
    "milongas": "Es un tipo de música de algunos países del sur de América.",
    "Minas de Ocre": "son los restos de una pequeña mina que hay en el camino del faro.",
    "Mítines ": "Son actos que realizan los partidos políticos para que los ciudadanos conozcan sus propuestas e ideas para organizar el país o la ciudad. Se realizan cuando se acercan las elecciones. ",
    "Mitología": "Es la historia imaginaria de dioses o héroes. Por ejemplo, de los dioses: Zeus Ares Hércules …",
    "Modernista": "Es un estilo de arte que usa formas sencillas y tiene pocos adornos",
    "Moluscos": "Es un animal sin vértebras y con cuerpo blando que suele ir cubierto de una concha. Por ejemplo, los mejillones.",
    "Monarquía absolutista": "En este tipo de gobierno el rey tiene todo el poder. Las personas no tienen derechos.",
    "monasterio": "Edificio donde viven juntos monjas o monjes.",
    "monedas virtuales y criptoactivos": "Son monedas que no se puede tocar y se usa a través de internet.",
    "monedas virtuales": "Son monedas que no se puede tocar y se usa a través de internet.",
    "criptoactivos": "Son monedas que no se puede tocar y se usa a través de internet.",
    "Monolito": "cartel que da información o explica el lugar o monumento que visitas.",
    "Mosaico": "Obra hecha con muchos trocitos de piedra o cristal de colores que forman un dibujo",
    "Mosaico": "son trozos pequeños de piedras formando un dibujo o un diseño que sirven para decorar suelos, techos o paredes.",
    "Motivos geométricos": "decorado con cuadrados, triángulos y círculos",
    "Música barroca": "Es un tipo de música que tocaban desde el siglo 16 hasta la mitad del siglo 18.",
    "Música de cámara": "Es la música que toca una orquesta pequeña con pocos instrumentos y que se toca en salas pequeñas.",
    "musical": "obra de teatro en la que hay música, los actores cantan, hablan y bailan",
    "Musicología": "es la ciencia que estudia la teoría y la historia de la música. ",
    "Musicólogo": "Es la persona que estudia la música y su historia.",
    "Musulmanes": "personas de religión islámica que vivieron en España desde el siglo 8 hasta el siglo 15. Ellos creen en un único dios (Alá) y en su profeta Mahoma. ",
    "Mutilación genital femenina": "Es dañar los órganos genitales femeninos sin motivos médicos.",
    "Nailon": "es un hilo elástico y muy fuerte.",
    "Nano máster": "Curso que se puede hacer después de estudiar una carrera en la Universidad y que tiene una corta duración. ",
    "Necrópolis": "sitio donde se encuentran enterrados restos humanos de culturas antiguas.",
    "Neoclásico": "es un estilo de arte que imita a los edificios que construían los griegos y los romanos.",
    "Nervio": "es un tubo pequeño por donde pasa el alimento de las flores.",
    "Neuro máster": "Curso que se puede hacer después de estudiar una carrera en la universidad y que tiene una corta duración.",
    "Neuropediatría": "Médico que estudia los problemas del sistema nervioso de los niños pequeños. ",
    "Neveros": "Es una construcción para conservar la nieve y que no se derrita.",
    "Newsletter": "es una publicación digital que da información de interés a través del correo electrónico.  La información puede ser diaria, semanal y mensual.",
    "Ninot": "Es una figura de cartón piedra o de otros materiales que es una parte pequeña de la hoguera",
    "No sexista": "Las cosas no se dividen en hombres y mujeres. Todo es para todos. ",
    "ñora": "pimiento de color rojo que se usa mucho en la cocina alicantina.",
    "ONGD Organización No Gubernamental para el Desarrollo": "Es una asociación que no pertenece a ningún país y que no quiere ganar dinero. Las ONGD ayudan a mejorar la vida de las personas.",
    "ONGs": "Es una asociación que no pertenece a ningún país y que no quiere ganar dinero. Las ONGs ayudan a mejorar la vida de las personas.",
    "Op-art": "Estilo de arte que crea movimiento al juntar y repetir figuras y formas sencillas como: - círculos - rectángulos - cuadrados - triángulos",
    "óperas": "Son obras de teatro en las que los actores cantan y están acompañados de una orquesta.",
    "Orfeón": "Es un grupo de personas que cantan sin instrumentos",
    "Orientación sexual": "A una persona le pueden gustar: personas del distinto sexo, personas del mismo sexo, personas de los 2 sexos.",
    "Orientalizante": "etapa final de la Prehistoria. Hay contactos de compra y venta con pueblos que vienen del Mediterráneo oriental, como fenicios y griegos.",
    "Ovalada": "forma parecida a un huevo.",
    "Países en desarrollo ": "Es un país que está mejorando pero que aún no tiene nivel normal en alimentación, salud, vivienda, educación.",
    "Países menos adelantados": "En estos países las personas ganan poco dinero no viven bien y tienen poca seguridad.",
    "Paleolítico": "es el periodo más antiguo de la Prehistoria. Los habitantes del Paleolítico vivían de la caza y de la recolección de frutos.",
    "Paleolítico Medio": "una época de la prehistoria",
    "Paleontología": "es la ciencia que estudia las formas de vida que existieron en la tierra a través de sus fósiles.",
    "Palmito": "Es la única palmera que nace y vive en Europa. Los demás tipos de palmeras que viven en Europa tienen su origen en otros lugares.",
    "Paneles de energía solar": "aparatos que utilizan los rayos del sol y los transforman en electricidad.",
    "Papel parafinado": "Es un tipo de papel como el que usamos para cocinar en el horno.",
    "Papel vegetal": "Es un tipo de papel casi transparente hecho de pasta vegetal que usan los dibujantes.  Parecido al papel de horno. ",
    "Parapente": "Es un deporte que consiste en tirarse con un parapente que es parecido a un paracaídas de un lugar alto. Por ejemplo: una montaña.",
    "Parque Natural": "zona muy bonita que tenemos que proteger.",
    "Partido político": "Grupo de ciudadanos que comparten las mismas ideas sobre la forma de organizar un país y que se unen para defenderlas y representarlas. ",
    "Patrimonio": "Son monumentos, pinturas, estatuas, instrumentos musicales, costumbres, bailes, que pertenecer a una comunidad. ",
    "Patrimonio cultural": "Lo forman: ● monumentos ● pinturas ● estatuas ● bailes ● instrumentos musicales ● costumbres que pertenecen a una comunidad.",
    "Patrimonio de la humanidad": "Título que concede la UNESCO a algunos espacios de interés cultural para protegerlos y que todos podamos disfrutar de ellos. La UNESCO es la Organización de las Naciones Unidas para la Educación, Ciencias y Cultura",
    "Patrimonio natural": "Son las plantas, los animales y los paisajes de un lugar que son importantes y que hay que cuidar y proteger.",
    "Peatonal": "solo puedes caminar y no pueden pasar coches, motos, bicicletas...",
    "Pedanía": "es como un pueblo, pero más pequeño.  Las pedanías pertenecen a un territorio y ayuntamiento de otro pueblo. ",
    "Península": "España y Portugal.",
    "Península Ibérica": "Es el pedazo de tierra formada por los países España, Portugal, Gibraltar y Andorra. ",
    "percusionista": "Es un músico que toca un instrumento de percusión. El instrumento de percusión produce sonidos cuando se golpea.",
    "Perenne": "son las hojas que no caen del árbol durante todo el año.",
    "Permanente": "Es algo que no cambia y dura mucho tiempo en el mismo lugar.",
    "Permisivo": "Persona que suele consentir o permitir las cosas. ",
    "Pesca de arrastre": "pesca que se hace arrastrando las redes por el fondo del mar.",
    "Pesca deportiva": "pesca que se hace como entretenimiento o deporte.",
    "Peste": "enfermedad muy contagiosa de la que murieron muchas personas.",
    "Pétalos": "es la parte coloreada de la flor.",
    "Pinada": "es un lugar con muchos pinos. El pino es un tipo de árbol.",
    "Pinares": "son bosques que tienen muchos pinos.",
    "Pintura rupestre": "son pinturas que se pintaban en las rocas y paredes de las Cuevas.  ",
    "Pinturas rupestres": "Son pinturas que se pintaban en las rocas y paredes de las cuevas",
    "Pira": "Hoguera donde hace muchos años quemaban los cuerpos de las personas muertas. ",
    "Piscicultura": "Es una actividad para criar peces y mariscos en estanques artificiales y naturales. ",
    "Piscifactorías": "lugar donde hay piscinas para criar peces.",
    "Planta trepadora": "crece sujetándose a paredes, otras plantas o rocas.",
    "Planta vivaz": "es una planta que vive más de dos años.",
    "Pobla Medieval de Ifach": "Opción1: Son unas ruinas amuralladas que se encuentran en la ciudad de Calpe junto al peñón de Ifach. Opción 2: es parte de una ciudad del siglo XIII (13) que tiene restos de almacenes, casas y una Iglesia.  Se encuentra en Calpe. ",
    "Podcast": "es un programa de radio que podemos descargar de internet para escucharlo en el móvil o en el ordenador. ",
    "Polen": "es un polvo fi no que encontramos en la punta del estambre de las flores y sirve para crear más flores en otras plantas.",
    "Poliéster": "Es un tipo de hilo muy fuerte y resistente.",
    "Polinizar": "transportar el polen de una planta a otra para que nazcan más plantas o flores.",
    "Pop-art": "Estilo de arte que coge ideas de imágenes y objetos de la cultura popular. Por ejemplo: - anuncios publicitarios - revistas - cómics - cine",
    "Posar": "Cuando una persona está en una posición sin moverse para servir de modelo a un fotógrafo, pintor o escultor.",
    "Posología": "Cantidad y tiempo entre las tomas de una medicación.",
    "Praderas": "son terrenos grandes y planos con hierba o plantas submarinas.",
    "Precarización": "un trabajo precario es un trabajo sin buenas condiciones.",
    "Prehistoria": "Opción 1: es una parte de la historia que va desde el origen del hombre hasta que aparece la escritura.  Opción 2: es el primer periodo de tiempo de la historia.",
    "Prejuicio": "Opinión negativa o positiva que tenemos sobre las cosas y personas.",
    "Prescripción": "Justificante firmado por un médico de la medicación de una persona.",
    "Prevención": "es algo que se hace antes para evitar que pase una cosa que es negativa.",
    "Proa": "parte delantera de un barco.",
    "procesión": "es un grupo de personas que caminan por la calle de forma ordenada y solemne para celebrar alguna fiesta religiosa.",
    "Productividad": "Es la cantidad de trabajo que realiza un trabajador en un período de tiempo.",
    "Productores": "son las personas elaboran un producto. ",
    "Productos básicos alimentarios": "Leche, carnes, huevos, legumbres, cereales, verduras y frutas.",
    "Programa de Respiro Familiar": "Recurso de atención a personas con discapacidad intelectual abierto todo el año las 24 horas del día. Es una vivienda adaptada y con apoyo.",
    "Protocolo": "Son normas que hay que cumplir para tener un comportamiento adecuado en un momento o tema concreto",
    "Provincia": "son las zonas de una Comunidad Autónoma. Por ejemplo, la Comunidad Valenciana tiene 3 provincias: Alicante, Valencia y Castellón.",
    "Proyecto": "es una cosa que se quiere hacer y se organiza para hacerlas bien y de una forma concreta. ",
    "Psiquiatra": "Médico especialista en enfermedades mentales y que puede dar medicamentos para el tratamiento.",
    "Psiquiátrico penitenciario": "hospital o centro para personas que están en la cárcel y necesitan atención de psiquiatras.",
    "pub": "es un local donde sirven bebidas y se escucha música",
    "Pueblo": "es el conjunto de personas que pertenecen a un país o tienen una misma cultura, lengua, raza o religión.",
    "Pueblo indígenas": "Persona que vive en un territorio respetando las costumbres y forma de vida antiguas.",
    "Pulperas": "herramienta que se utiliza para pescar pulpos.",
    "Púnica": "que era de una ciudad antigua de África llamada Cartago",
    "Puñales": "es un arma con forma de cuchillo",
    "Pupila": "es el círculo de color negro que hay en el centro del ojo.",
    "Racimo": "es un grupo de flores que crecen juntas en un único tallo.",
    "Ramillete": "es un ramo pequeño.",
    "Real Decreto": "Es una ley que hace el Gobierno en caso extraordinario o necesidad urgente.",
    "Recinto fortificado": "Construcciones para defender un lugar.",
    "Rector/a": "Es la máxima autoridad académica de la Universidad.",
    "Recurso": "ayuda para que una persona pueda conseguir un objetivo o las cosas que necesite.",
    "Recursos marinos": "Son todos los seres vivos que viven en el mar.",
    "Redera": "Es la persona que hace las redes de pesca.",
    "Reforestación": "Reforestación es plantar muchos árboles en terrenos en los que ya no hay.  ",
    "Refugio": "lugar que las personas usaron durante la guerra para esconderse y protegerse de las bombas.",
    "regata": "competición deportiva de barcos de vela. En esta competición los barcos tienen que hacer un recorrido en el menor tiempo posible.",
    "Régimen constitucional": " en este tipo de gobierno hay leyes y las personas tienen derechos.",
    "Reglamento": "son varias normas que hay que seguir para que algo funcione bien",
    "Rehabilitación": "arreglar o mejorar algo. Por ejemplo, hacer rehabilitación para volver a mover la mano después de una operación.",
    "Reinserción:": "volver a integrar a una persona en la sociedad después de haber estado en la cárcel. ",
    "Relieve": "Algo que sobresale en una superficie plana.",
    "relieve": "dibujos o formas que sobresalen de una superficie.",
    "Relieve cerámico": "es una parte que sobresale hecha de cerámica. ",
    "renacentista herreriano": ": es un estilo de arte muy sencillo que tiene muy pocos adornos. ",
    "Reprografía": "lugar donde puedes ir a imprimir o fotocopiar documentos y muchas cosas más. ",
    "Reptil": "es un animal que: ● Tiene pulmones ● Tiene escamas en la piel ● Nace de un huevo ● Algunos tienen caparazón, como la tortuga ● Tiene un esqueleto bajo la piel ● Tiene patas cortas o no tiene patas, como la serpiente",
    "Reserva marina": "zona protegida en la que se permite el baño, pescar con caña y bucear sin botella.",
    "restos ": "son ruinas y objetos que pertenecen a pueblos más antiguos",
    "restos arqueológicos": "objetos y restos de otras épocas más antiguas.",
    "Roma ": "ciudad que pertenece al país que se llama Italia. ",
    "Romanización": "fue un periodo en el que los pueblos de la antigua Roma conquistaban territorios que no eran romanos. Después de un tiempo, los pueblos no romanos hablaban la lengua de Roma y tenían las costumbres y la religión del imperio romano. ",
    "romanos": "fueron las personas que conquistaron España a los íberos hace muchísimos años.",
    "Romería": "fiesta popular en la que mucha gente camina hasta el lugar donde hay un santo",
    "Ronda de Doha": "Reuniones que tienen los países desarrollados para poner normas en el comercio con los países en vías de desarrollo.",
    "Running": "deporte que consiste en correr",
    "Ruta": "camino que va de un sitio a otro.",
    "Sacerdote": "Persona que se dedica a realizar actos de una religión. Es parecido a un cura. ",
    "Sala temática": "Opción 1: Es el lugar donde puedes aprender sobre un tema.  Opción 2: es un espacio de exposiciones sobre diferentes temas. ",
    "Salazones": "son carnes y pescados que se conservan en sal.",
    "Salmuera": "es una forma de conservar alimentos. Hundes las hojas en agua, sal y vinagre durante un tiempo y después puedes comer las hojas.",
    "Salud reproductiva y sexual": "Incluye el buen funcionamiento del aparato reproductor y la posibilidad de tener una sexualidad sana.",
    "Salvia": "es un líquido que circula por la planta y que sirve para alimentarse.",
    "Saneamiento": "Lograr que todas las personas puedan usar un aseo con agua limpia para tener una higiene adecuada.",
    "Santuario": "lugar sagrado",
    "Scape Room": "Scape Room o sala de escape, es un juego en el que los jugadores están encerrados en una habitación y para ganar la partida tienen que resolver pruebas.  ",
    "Sector": "Es una zona o parte de algo",
    "Semilla": "grano que crece dentro de una fruta. Del grano crecerá otra planta.",
    "Seminario": "Son unas jornadas donde profesores y alumnos hacen actividades para investigar sobre un tema.",
    "Semisótano": "Local que está debajo del nivel de la calle",
    "seres vivos": "-        los pájaros -        los insectos -        las plantas -        las personas Entre otros",
    "Serigrafía": "Es una forma de pintar con tinta. Ponemos la tinta en una malla que está en un marco y luego apretamos la malla sobre el papel o la tela para que pase el dibujo.",
    "Servicios básicos": "Son cosas que hay en una ciudad y que nos ayudan a vivir bien y de manera saludable.  Por ejemplo: agua para beber alcantarillas calles y carreteras luces en las calles electricidad en las casas policía atención médica colegios",
    "Servicios financieros": "Son los servicios que nos prestan dinero a personas o empresas.",
    "SIDA, la tuberculosis, la malaria y enfermedades tropicales:": "Son enfermedades que se contagian de manera rápida y si no son tratadas por médicos pueden causar la muerte.",
    "Sierra ": "Es un grupo de montañas dentro de otro grupo más grande. La parte alta de estas montañas se caracteriza por tener una forma parecida a una sierra de cortar madera.",
    "Sierra Helada": "es un parque natural que está entre el pueblo de Benidorm y el de Alfaz del Pi.",
    "Siglo": "1 siglo son 100 años",
    "Siglo": "1 siglo son 100 años.",
    "Siglo de Oro": "Época de los siglos 16 y 17 muy importante para el arte, las letras y la cultura en España. Duró más de 150 años.",
    "Sillares": "piedra tallada o piedra muy bien cortada.",
    "Silvestre": "que crece de forma natural en el campo o bosques sin ayuda de las personas.",
    "Silvicultura": "Es una actividad para cultivar y mantener los bosques y cuidar el medioambiente. ",
    "Sistemas de descalcificación": "Son aparatos que sirven para quitar la cal del agua.",
    "Soldadura": "Es la unión de 2 o más piezas del mismo material. Por ejemplo, el hierro o el plástico.",
    "Solidaridad": "Es ayudar sin recibir nada a cambio.",
    "Solidario": "ser bueno o generoso con otras personas que lo necesitan.",
    "Soprano": "Es una mujer que canta ópera.",
    "Soprano, Barítono y Contratenor": "Son cantantes con diferentes tipos de voz que puede ser más fuerte o más suave.",
    "Sostenible": "Es cuando usamos todo lo que hay en la naturaleza sin ponerla en peligro para no destruirla.",
    "Subasta de pescado": "En la subasta se vende pescado y lo compra la persona que paga más dinero.",
    "Subvencionadas": "Es cuando una persona o centro recibe una ayuda en dinero para hacer alguna actividad. ",
    "Subvencionar": "Dar dinero a las asociaciones para realizar actividades.",
    "Paddle-surf": "Es un deporte que se practica de pie sobre una tabla de surf y el deportista utiliza un remo para moverse por el agua.",
    "Surf": "deporte que se practica en el mar deslizándose sobre las olas en una tabla.",
    "Surrealismo": "El surrealismo es un movimiento literario y artístico que busca trascender lo real a partir del impulso psíquico de lo imaginario y lo irracional",
    "Swing": "es un tipo de música jazz con mucho ritmo.",
    "Talar": "Cortar un árbol por el tronco",
    "Tallo": "es la parte de la planta donde crecen las hojas.",
    "Tallo leñoso": "el tallo es la parte de la planta donde crecen las hojas. Leñosos significa que son de madera muy fina.",
    "Tapiz": "Opción 1: Es parecido a un cuadro de tamaño grande que está hecho con hilos de colores. Opción2: Es una obra de tela hecha con diferentes tipos de hilos o lanas. ",
    "Tardorromano": "Es la última época del imperio romano.  ",
    "Telares": "máquina para fabricar telas",
    "Tenor": "Es un hombre que canta ópera.",
    "Terracota": "es arcilla que se mete al horno para hacerla más dura y hacer figuras",
    "Teselas": "Son trozos pequeños de piedras de colores que se usan para hacer mosaicos",
    "Testador": "es la persona que hace el testamento",
    "Testar": "es hacer un testamento.",
    "Tintes vegetales": "Son pinturas que sacamos de las plantas y los minerales.",
    "Tirolina": "Sistema de cuerdas o cables en altura que sirve para deslizarte por ellos y llegar de un punto a otro. ",
    "TRAM ": "tranvía de la ciudad de Alicante. Tiene paradas en El Campello y Playa de Muchavista.",
    "Transición": "Es cuando algo está cambiando",
    "Transporte público": "Son los trenes, los taxis, y los autobuses. También el tranvía.",
    "Trasmallo": "forma de pesca con 3 redes: • 2 exteriores con mismos huecos en la red. • 1 central con huecos más pequeños.",
    "Tribunal Constitucional": "es una institución que defiende el respeto a la Constitución. Revisa las leyes y dice si la ley cumple con la Constitución.",
    "Tubérculo": "es un tallo que crece dentro de la tierra y es muy grueso.",
    "Tunecinos": "son las personas que pertenecen al país que se llama Túnez",
    "Turbante": "trozo de tela que se pone en la cabeza",
    "Turismo sostenible": "Es el turismo que cuida el medio ambiente y la cultura de su ciudad.",
    "UNESCO": "es una organización que ayuda a los países a ser más modernos sin perder su cultura.",
    "Unidades de Apoyo": "Es un grupo de profesionales de distintas materias que apoyan a los trabajadores con discapacidad en los Centros Especiales de Empleo",
    "Uniones de hecho": " Es cuando 2 personas viven juntas porque se quieren, pero no están casados.",
    "Upapsa": "Unión Provincial de Asociaciones de Personas con Discapacidad Intelectual de Alicante.",
    "Vagoneta": "Carro pequeño y sin techo que sirve para transportar mercancías.",
    "Vaina": "es cuando la hoja hace un envoltorio para guardar dentro las semillas.",
    "Valores": "Son las características buenas de una persona.",
    "Vanguardismo": "Estilo de arte que busca experimentar y crear cosas nuevas.",
    "Vega Baja del Segura": "Es una zona que está al sur de Alicante.",
    "Venecia": "ciudad que pertenece al país que se llama Italia. ",
    "Vertical": "que van de arriba a abajo.",
    "Vida cultural ": "Es participar en cine teatro televisión libros conciertos de música",
    "Villa": "Casa de recreo situada aisladamente en el campo.",
    "Viola de gamba": "Es un instrumento musical de cuerda parecido al violín, pero más grande.",
    "Violencia de género": "Violencia física o emocional que sufre una mujer por parte de un hombre por el hecho de ser mujer.",
    "Vitrina": "armario con puertas de cristal que sirve para proteger y ver los objetos que se guardan dentro.",
    "Voluntariado": "Es dedicar tiempo a ayudar a los demás y a la sociedad sin cobrar dinero por ello. ",
    "Voluntariado corporativo": "Es el voluntariado que hacen los trabajadores de una empresa.",
    "Vulnerabilidad social": "Una persona es vulnerable en la sociedad cuando por su situación social, económica o por su lugar de origen tiene mayor riesgo de ser pobre",
    "Vulnerable": "Es una persona que, por su situación, social, económica o por su lugar de origen tiene mayor riesgo de ser pobre.",
    "Windsurf": "Deporte que se practica en el mar deslizándose sobre las olas en una tabla que lleva una vela. ",
    "Yacimiento": "Opción 1: Lugar donde hay restos arqueológicos.  Opción 2: Lugar donde encontramos restos de otras épocas de la historia.",
    "Yacimiento arqueológico": "es un lugar en el que hay objetos y restos de otras épocas más antiguas",
    "Yacimientos arqueológicos": "Yacimientos arqueológicos: lugares donde se encuentran restos arqueológicos muy antiguos.",
    "Zócalo": "línea horizontal que se utiliza para decorar o proteger la parte de abajo.",
    "Zonas verdes": "Son lugares que tienen: plantas césped árboles bancos para sentarte",
    "Convención": " Acuerdo entre países para seguir unas normas iguales sobre algún tema.",
    "Consolidar": "Asegurar",
    "Ratificar": "confirmar que estás de acuerdo con algo. ",
    "Cortes Generales": "son las encargadas de hacer y votar las leyes de España.",
    "BOE": "significa Boletín Oficial del Estado y es donde publican las leyes de España nuevas o modificadas. ",
    "Preámbulo": "es una introducción o pequeño resumen con las ideas del texto que se dicen al principio de todo. ",
    "Barrera": "Impiden que una persona con dificultades pueda hacer lo mismo que los demás. "

        }
